#!/usr/bin/env bash
# Read file and manipulate fields to generate story

FILE="/etc/passwd"

while  IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID User_Information HOME_DIRECTORY SHELL
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $User_Information"
done < "$FILE"
