#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints hi in the 9 time

i="0"

while [ $i -lt 10 ]
do
    if [ $i == 9 ]
    then
        echo "Hi";
    fi
        echo "Best School";
    (( i++ ));
done

# i=1
# while [ "$i" -le 10 ]
# do
#     echo "Holberton School"
#     if [ "$i" -eq 9 ]; then
# 	echo "Hi"
#     fi
#     (( i++ ))
# done
