#!/usr/bin/env bash
# This script the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 5

hours="0"
minutes="1"

echo "Hour: 0";

while [ $hours -le 12 ]
do
    echo "$minutes"

    if [ $minutes -eq 59 ]
    then
        (( hours++ ));
        if [ $hours -lt 13 ]
        then
            echo "Hour: $hours";
        fi
        (( minutes=0 ));
    fi

    (( minutes++ ));
done
